<a href="https://colab.research.google.com/github/julianVelandia/RedesNeuronalesConPyTorch/blob/master/conocimientos-previos/1_4_introduccion_a_numpy_FULL.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introducción a NumPy

Una de las bibliotecas más populares en Python para la manipulación de arrays y computación numérica. NumPy es esencial para cualquier trabajo en ciencia de datos, aprendizaje automático, y cualquier disciplina que requiera operaciones matemáticas rápidas y eficientes.

In [ ]:
import numpy as np

Es usual que se importe con el alias de np

## Creación de Arrays

Un array es una estructura de datos similar a una lista en Python, pero mucho más eficiente para operaciones numéricas. NumPy permite crear arrays de múltiples dimensiones.

In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print('Array de una dimensión:', arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print('Array de dos dimensiones:\n', arr_2d)

arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print('Array de tres dimensiones:\n', arr_3d)

Array de una dimensión: [1 2 3 4 5]
Array de dos dimensiones:
 [[1 2 3]
 [4 5 6]]
Array de tres dimensiones:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Atributos de los Arrays

Los arrays de NumPy tienen varios atributos importantes que puedes utilizar para obtener información sobre ellos.

In [ ]:
print('Forma del array 2D:', arr_2d.shape)
print('Número de dimensiones del array 3D:', arr_3d.ndim)
print('Número total de elementos en el array 1D:', arr_1d.size)
print('Tipo de dato en el array 2D:', arr_2d.dtype)

Forma del array 2D: (2, 3)
Número de dimensiones del array 3D: 3
Número total de elementos en el array 1D: 5
Tipo de dato en el array 2D: int64


## Indexación y Slicing

La indexación y el slicing en arrays de NumPy son similares a las listas en Python, pero con mayor flexibilidad para trabajar con arrays multidimensionales.

In [ ]:
print('Primer elemento del array 1D:', arr1[0])
print('Último elemento del array 1D:', arr1[-1])
print('Slicing del array 1D (primeros 2 elementos):', arr1[:2])
print('Slicing del array 1D (todos menos el primero):', arr1[1:])
print('Slicing del array 1D (todos menos el último):', arr1[:-1])

Primer elemento del array 1D: 1
Elemento en la posición (1, 2) del array 2D: 2
Slicing del array 1D (primeros 3 elementos): [1 2 3]
Slicing del array 2D (columna 2):
 [2 5]


## Operaciones Matemáticas con Arrays

Una de las grandes ventajas de NumPy es que permite realizar operaciones matemáticas sobre arrays enteros de manera eficiente, sin necesidad de bucles.

In [ ]:
arr_sum = arr_1d + np.array([10, 10, 10, 10, 10])
print('Suma de arrays:', arr_sum)

arr_mult = arr_1d * 2
print('Multiplicación por un escalar:', arr_mult)


Suma de arrays: [11 12 13 14 15]
Multiplicación por un escalar: [ 2  4  6  8 10]
Producto punto: 11


In [ ]:
arr_a = np.array([1, 2])
arr_b = np.array([3, 4])
dot_product = np.dot(arr_a, arr_b)
print('Producto punto:', dot_product)

Matemáticamente, si tenemos dos vectores
a = [a1, a2] y b = [b1, b2], el producto punto a ⋅ b se calcula como:

a ⋅ b = a1 × b1 + a2 × b2

Aplicando esto a nuestros vectores `arr_a` y `arr_b`:

dot_product = 1 × 3 + 2 × 4 = 3 + 8 = 11


## Funciones Universales (ufuncs)

NumPy proporciona un conjunto de funciones universales (ufuncs) que permiten realizar operaciones matemáticas comunes de manera eficiente sobre arrays.

In [ ]:
arr_sin = np.sin(arr_1d)
print('Seno de cada elemento en arr_1d:', arr_sin)

arr_exp = np.exp(arr_1d)
print('Exponencial de cada elemento en arr_1d:', arr_exp)

Seno de cada elemento en arr_1d: [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]
Exponencial de cada elemento en arr_1d: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


## Manipulación de la Forma del Array (Reshaping)

Es posible cambiar la forma de un array sin alterar sus datos utilizando la función reshape. Esto es útil cuando quieres reorganizar los datos en diferentes dimensiones.

In [ ]:
print('Array 1D original:', arr_1d)

arr_reshaped = arr_1d.reshape((1, 5))
print('Array 1D reshaped a 2D:\n', arr_reshaped)

arr_reshaped_3d = arr_1d.reshape((5, 1, 1))
print('Array 1D reshaped a 3D:\n', arr_reshaped_3d)

Array 1D original: [1 2 3 4 5]
Array 1D reshaped a 2D:
 [[1 2 3 4 5]]
Array 1D reshaped a 3D:
 [[[1]]

 [[2]]

 [[3]]

 [[4]]

 [[5]]]


## Broadcasting

Broadcasting es una poderosa característica de NumPy que permite realizar operaciones entre arrays de diferentes formas, expandiendo automáticamente las dimensiones de los arrays más pequeños para que coincidan con los más grandes.

In [ ]:
arr_broadcast = arr_2d + 10
print('Broadcasting (sumar escalar 10):\n', arr_broadcast)

Broadcasting (sumar escalar 10):
 [[11 12 13]
 [14 15 16]]


arr_2d es un array bidimensional (una matriz).

Broadcasting expande automáticamente el escalar 10 para que coincida con la forma del array arr_2d. Internamente, NumPy "repite" el escalar 10 tantas veces como sea necesario para que tenga la misma forma que el array arr_2d.

In [ ]:
np.array([[1, 2, 3],
          [4, 5, 6]])

# Sumado con

[[10, 10, 10],
 [10, 10, 10]]

# Da como resultado:

[[1 + 10, 2 + 10, 3 + 10],
 [4 + 10, 5 + 10, 6 + 10]]


[[11, 12, 13], [14, 15, 16]]

In [ ]:
arr_broadcast_2 = arr_2d + np.array([1, 2, 3])
print('Broadcasting entre array 1D y 2D:\n', arr_broadcast_2)

Broadcasting entre array 1D y 2D:
 [[2 4 6]
 [5 7 9]]


In [ ]:
np.array([[1, 2, 3],
          [4, 5, 6]])

# Sumado con

[[1, 2, 3],
 [1, 2, 3]]

# Da como resultado:

[[1 + 1, 2 + 2, 3 + 3],
 [4 + 1, 5 + 2, 6 + 3]]

[[2, 4, 6], [5, 7, 9]]

## Agregación y Estadísticas

NumPy ofrece una serie de funciones de agregación que permiten calcular estadísticas sobre los datos de los arrays de manera sencilla.

In [ ]:
print('Suma de todos los elementos en arr_1d:', np.sum(arr_1d))
print('Promedio de los elementos en arr_1d:', np.mean(arr_1d))
print('Valor máximo en arr_2d:', np.max(arr_2d))
print('Índice del valor máximo en arr_2d:', np.argmax(arr_2d))

## Concatenación de Arrays

Puedes unir múltiples arrays utilizando las funciones de concatenación de NumPy. Esto es útil para combinar datos en diferentes ejes.

In [ ]:
arr_concat = np.concatenate([arr_1d, np.array([6, 7, 8])])
print('Concatenación de arrays 1D:', arr_concat)

arr_2d_concat = np.concatenate([arr_2d, arr_2d], axis=0)
print('Concatenación de arrays 2D a lo largo de filas:\n', arr_2d_concat)

arr_2d_concat_col = np.concatenate([arr_2d, arr_2d], axis=1)
print('Concatenación de arrays 2D a lo largo de columnas:\n', arr_2d_concat_col)

Concatenación de arrays 1D: [1 2 3 4 5 6 7 8]
Concatenación de arrays 2D a lo largo de filas:
 [[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
Concatenación de arrays 2D a lo largo de columnas:
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
